### Create user
POST http://localhost:8080/user/register HTTP/1.1
content-type: application/json

{
    "name": "sample3",
    "password": "password1"
}

### Get token
POST http://localhost:8080/user/login HTTP/1.1
content-type: application/json

{
    "name": "sample3",
    "password": "password1"
}

### Get token
POST http://localhost:8080/user/login HTTP/1.1
content-type: application/json

{
  "name": "aa",
  "password": "a"
}